### ISSUE TITLE
[BUG] Seems the planet search endpoint is not providing distances back

### ISSUE THREAD

**Issue by baxterchippy** [jplacht/fio_wrapper#19]
# Description
When I call the planet.search() method it doesnt return distances.

# Reproduction
locDistance = fio.Planet.search(include_rocky=True, distance_checks=["ANT", "MOR"])

```

Expected distances from the planets

**Comment by jplacht** [comment]
Additionally by info from Saganaki: Planet Search allows for up to `10` instead of `3` distances to check.
